# Generated by Django 4.1.2 on 2022-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="publications",
            field=models.ManyToManyField(to="api.publication"),
        ),
    ]
