# Generated by Django 4.1.2 on 2022-10-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_publication_num_citations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="scholar_id",
            field=models.TextField(unique=True),
        ),
    ]
